### PR TITLE
Clarify initial governance steps

### PR DESCRIPTION
**Pull request by ttx**
Refactor the README into a set of documents and clarify the initial governance steps, as discussed in various meetings.

### CODE REVIEW

**Review by PARitter — CHANGES_REQUESTED** [review]
@ttx I think that this organization of the documents is an improvement over the original reame.md, but as written the governance.md document is too thin.  It leaves too much to be defined later by the "bootstrapping committee".  At a minimum, I think "step 1" needs to become "Interim Governance" that discusses the initial set of Maintainers in addition to the "release management team".  And step two needs to be a bit more proscriptive about how the permanent Governance structure will be formed.

**Comment by ttx** [comment]
Thanks @PARitter for your comments. I just pushed a new version that should help address your concerns. My goal is mostly to describe the current state and not be too prescriptive on what the next step will look like. This can be proposed as a subsequent change and be judged on its own merit.

**Review by PARitter — CHANGES_REQUESTED** [review]
@ttx I understand the interim nature of this version but I do think the "governance" document needs to align with the collaboration agreement being put together by OIA, OIF and TIP.  Because of that I think it needs to note the formation of the initial technical committee and that the TC will be responsible for further updates to Governance documents.

Apologies for being picky...

**Comment by ttx** [comment]
@PARitter is the latest version working for you?

**Pull request merged**
